services:
  - type: web
    name: grifo-api-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://app.grifovistorias.com,android-app://com.grifo.vistorias,http://localhost:3000,https://portal.grifovistorias.com,https://grifo-portal.netlify.app,https://grifo-portal-v1.netlify.app
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: JWT_SECRET
        value: grifo_prod_jwt_secret_2024_banco_visionaria_secure_key
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BYPASS_AUTH
        value: false
      # Firebase Configuration
      - key: FIREBASE_API_KEY
        value: AIzaSyDRj2kodgFUW2-N1Boa5nP5IZYVg-HaJME
      - key: FIREBASE_AUTH_DOMAIN
        value: banco-visionaria.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: banco-visionaria
      - key: FIREBASE_STORAGE_BUCKET
        value: banco-visionaria.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 806439611518
      - key: FIREBASE_APP_ID
        value: 1:806439611518:web:591fc6ca38cb4459737c2f
      - key: FIREBASE_CREDENTIALS
        value: '{"type":"service_account","project_id":"banco-visionaria","private_key_id":"7173463b61bedc941727bed2a7cac44886c4dc3d","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCq2ml450RHU/Wl\nlcrGQNaH9o4Tv624s2VoOU55tiLctB3BHQOF6jBJBAoszqxDflVItczx5GBDRyDG\nvkbdU24eUjbuRSNqg49WUiVuMiCCuyhjkznOJnF+/tK3IHjxJiC+gpj2zc3Eo3cz\nwtY1TVg+kenWedKmD00LP4CCZi2uzB7ZAXw1bjpEKEqlDTOoKFpu7qOQzsMhjaML\n8BjQKXhPQ2ZwxQ3PoS+fF9YLz0WTpsqIBZKEXHlEOn5MnmyIw44rz6ni9+WCu8sM\n28YI8BVVH65eiU6IPsADWn2p3/H/E8yqIcD51NtP2X++GR0vd8titt1UqU6QVzHC\n2fPN0JVRAgMBAAECggEADA8oAChkrZsrvMEGo7kqW0ToENVH7AA/kVxwIU+dhNHy\nwrFrUP2vZEv0cuawioAFgYERguZRdBY2ZkjCZDdSD7JSXb2ECy3XhWp9aVqA6HFQ\n37xhyV71xlaypUnVt4GvMHsz1EHA+xbloEHpkDASITJ33JNTLrToRXm5NpsDMPHq\nL4BdEuz7swKXlAoW1RacteNJEunDXC15W5p3Ktoz37soVhoLdrB8eyI5M+qyuLhQ\nWYcvSxD6ql3K6Bri3UZvvXE7xjHZstF62F7swTp94F4ef8/jxmuCcHPRm0yov8Rk\nU8A/bCx19A4lhxcaRFRz+13OzHr3YpSWoSoctAjbcQKBgQDoraYAt5v9Rn3MgTeK\nuXVV782Kq5edknJe4M9bhycVqRUD97hGaOsJlIEspxd/jS6G2Rqmrbu3W9vXofEA\nfHvgu+qScYA5pLsGRlwzbpmtFQRo6ILHs+Ttzvtzqo9eY+FD0N310rhjvW/BNq/5\n8VKeeOPrIkXsur4trgm5Cdx8qQKBgQC7+mBq4vhZMC1tizf/Hkv7L2wy79KPh3Nl\npXVJnamlKReCvKg+8Q5wHElprDnHadI7wBl854+9nQX9xHbwbo0otIHPJ/5aWjWH\nT+YErsXcaHOMvu5vIDWijpCmdR+79/+u/EranIpUGLk2GM0/AC1gZEtjvlIRRGF7\nacOwH+pUaQKBgAJCDSZcocrncDkX1+4ktprK5Pe/io0g6rM5A0okGaEALxAGy2cD\nhaRmKIrCZFv8hsMQQE31yaiR36RMEgarLpiTukcJivEERDxfWm21WRBw78YE26AM\nguA77fzFXvbPiVQbJsxH6zoskHUTjsmiKecXzT5u6rbNaSMQWU/OZLFhAoGAR251\nhSiKxxmPqbjlpoSUyvbSXujTUsdeCpo9X6QR+zkKPhwCsyhXHDMjkoxnyGdmBF6T\nUOuNq7gntq8Zo3PfIEC3s0i3Vw5AmRK7jbv8ZC0s+6byZDgRKZyTSy3myT8MYipt\nJ3Wk+yAKAYybMf2XQLHcFCMWfIlHoeYm/p6iJUECgYBxvzVL9dShd6ExLuLvlnNA\n8gcm+WQcuTK6l7BNGTOuEumVp4zHzn9mas7Ytnx0g22IJaePu4/TK00POwy8biL9\nMBFZbEZJQq0Dyed9PSq20wo2MEQpH5Tnmu3L/719KYgo/dfAjvBLBCcYD1tHn8CP\nfClJTX85CEQX8tQOxG6hog==\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-fbsvc@banco-visionaria.iam.gserviceaccount.com","client_id":"104590279504460543318","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40banco-visionaria.iam.gserviceaccount.com","universe_domain":"googleapis.com"}'
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
