services:
  - type: web
    name: grifo-api-backend
    env: node
    plan: free
    repo: https://github.com/Nathan-Paranhos/grifo-api-backend.git
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      # API Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      
      # JWT Configuration
      - key: JWT_SECRET
        value: grifo_prod_jwt_secret_2024_banco_visionaria_secure_key_v2
      - key: JWT_REFRESH_SECRET
        value: grifo_prod_jwt_refresh_secret_2024_banco_visionaria_secure_key_v2
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      
      # Database Configuration (PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: grifo-database
          property: connectionString
      - key: DATABASE_HOST
        fromDatabase:
          name: grifo-database
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: grifo-database
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: grifo-database
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: grifo-database
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: grifo-database
          property: password
      
      # CORS Configuration
      - key: CORS_ORIGINS
        value: https://app.grifovistorias.com,android-app://com.grifo.vistorias,https://portal.grifovistorias.com,https://grifo-portal.netlify.app,https://grifo-portal-v1.netlify.app,https://grifo-api.onrender.com
      - key: CORS_ORIGIN
        value: https://app.grifovistorias.com,https://portal.grifovistorias.com,https://grifo-portal-v1.netlify.app
      - key: CORS_ALLOWED_ORIGIN
        value: https://grifo-portal-v1.netlify.app
      
      # Upload Configuration
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_MAX_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: UPLOAD_ALLOWED_TYPES
        value: image/jpeg,image/png,image/gif,application/pdf
      
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      
      # Logging
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE
        value: ./logs/app.log
      
      # Development Flags
      - key: BYPASS_AUTH
        value: false
      - key: DEBUG_MODE
        value: false
      

      
      # Portal Web Integration
      - key: PORTAL_ENABLED
        value: true
      - key: PORTAL_BASE_URL
        value: ""
      - key: PORTAL_API_KEY
        value: ""
      - key: PORTAL_TIMEOUT
        value: 30000
      - key: PORTAL_MAX_RETRIES
        value: 3
      
      # Firebase Configuration (as secret file)
      - key: FIREBASE_CREDENTIALS
        fromSecret: true
    
    # Health Check Configuration
    healthCheckPath: /api/health
    
    # Deployment Configuration
    autoDeploy: true
    branch: main
    
    # Build Filter
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - "*.md"
        - ".gitignore"
        - ".env*"
        - "node_modules/**"
        - "dist/**"

# Database Configuration
databases:
  - name: grifo-database
    databaseName: grifo_production
    user: grifo_user
    plan: free
