services:
  - type: web
    name: grifo-api-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        value: grifo_prod_jwt_secret_2024_banco_visionaria_secure_key
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGINS
        value: https://grifo-portal-v1.netlify.app,https://app.grifovistorias.com,android-app://com.grifo.vistorias,https://portal.grifovistorias.com,https://grifo-portal.netlify.app,https://visio-portal.netlify.app,https://www.visio-portal.com,https://www.grifo-portal.com,https://grifo-api.onrender.com,http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:5173
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: LOG_LEVEL
        value: info
      - key: BYPASS_AUTH
        value: false
      - key: PORTAL_ENABLED
        value: true
    healthCheckPath: /health
    autoDeploy: true
    branch: main