# Configuração para deploy no Netlify

[build]
  command = "npm run build"
  publish = "dist"

# Configuração para SPA (Single Page Application)
[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://grifo-api.onrender.com"

# Configuração de redirecionamento para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200